backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "producto" # Used in routes, e.g., /admin/collections/blog
    label: "Producto" # Used in the UI
    folder: "static/_productos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "producto"}
      - {label: "Nombre", name: "nombre", widget: "string"}
      - {label: "Descripcion Corta", name: "description", widget: "string"}
      - {label: "Cuerpo", name: "cuerpo", widget: "markdown"}
      - {label: "Categoria", name: "ProductoCategoria", collection: "categoria", displayFields: "nombre", searchFields: ["nombre", "descripcion", "cuerpo"]}
  - name: "categoria"
    label: "Categoría"
    folder: "static/_categorias"
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "categoria"}
      - {label: "Nombre", name: "nombre", widget: "string"}

